### PR TITLE
Fixed CoC link syntax

### PR DESCRIPTION
**Pull request by TwinProduction**
The link was not correctly displayed because there was a space between the [title] (http://and/the/url)

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Looks good. Thanks for the fix, @TwinProduction!

**Comment by caitmuenster** [comment]
Thanks so much @TwinProduction! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#April_2018). 

Would you be interested in creating an account on [mozillians.org](https://mozillians.org/)? I'd be happy to vouch for you!

**Comment by TwinProduction** [comment]
@caitmuenster Just created an account [here](https://mozillians.org/en-US/u/TwinProduction/), thank you.

**Comment by caitmuenster** [comment]
You are vouched! Welcome onboard. I look forward to seeing you around the project. :)

**Pull request merged**
