### PR TITLE
Initial addons submission and management UX

### PR DESCRIPTION
**Pull request by brampitoyo**
Inspired by Jorge’s proposal.

* Eliminated preliminary review
* Auto-approve and sign self-hosted/unlisted add-on. Review for sideloading is done later.
* Channel-based submission and management (release, beta & self-hosted, directly parallel to Jorge’s proposal of listed, listed beta & unlisted)
* File status refactoring (awaiting review, approved, rejected)
* Each version now has a review notes and history view, giving us one place to deliver review message, and for developers to submit their review notes, updated add-ons, proprietary source code, etc.

Source:
https://docs.google.com/document/d/1OH2iZ7aT9otFJvGTX1UR6pAm58u7ph2Uw8_Zv2Sl8Tk/edit

### CODE REVIEW

**Comment by brampitoyo** [comment]
Ping @jvillalobos @wagnerand @magopian @designakt  and @lisabrewster, for your thoughts and feedback.

After this push is merged, maybe give your feedback by filing a new issue, so I can then mark it as fixed when it’s finished.

**Comment by designakt** [comment]
Hey @brampitoyo, this is great. More design work on github.
What exactly is it you want feedback on? 

The idea of simplifying everything down to 3 different channels with the possibility to easily move versions between those seams very appealing.
https://github.com/brampitoyo/addons/blob/25e3daf2b29f8853f60a808db99509f667f256c1/docs/images/ux-management-flow.png

What made you decide to separate the channels from 1 list into 3 different tabs?
https://github.com/brampitoyo/addons/blob/d0c63a8e7554a385ddb1d6a048ca6da99277e739/docs/images/ux-management-wireframes.png

Without fully understanding the use cases we are trying to solve here I am having a hard time giving feedback. I am sure that will disappear as soon as we start getting results from the developer research. (Do you have a set of use cases you expect?)

**Comment by brampitoyo** [comment]
@designakt I’m looking to start the redesign process a bit earlier – based on what we’ve already heard from interviewing staff members.

I’m also looking for a confirmation of whether this direction matches the direction that the product is moving in, instead of being completely off base. In that regard, @jvillalobos @wagnerand and @magopian’s comment would be most helpful.

But first, let’s merge the change.

**Comment by jvillalobos** [comment]
Very nice! I like the new flow a lot. I have some notes on the wireframes:

1. "If more than X% sideloaded installed". This happens after the add-on has been auto-signed and we can't really unsign a version. What we would do is admin-disable the version, and maybe blocklist it if really necessary.
2. Disconnecting the "Listing information" step from the entire process would be tricky. When an add-on is awaiting its first review, we allow the add-on page to be accessible to people who have the URL, so at least the required metadata should be entered. We would need to do some juggling with the add-on status to make this work (like keep the add-on as Incomplete while it's pending review and doesn't have the metadata, and only allow access to the page if the state is Pending Review rather than Incomplete).
3. I think that moving/copying versions between channels is generally unnecessary and would add a lot of complexity. In particular, the presence or lack of an updateURL means we would need to tamper with the file when moving between Listed and Unlisted. It's easier for developers to just upload new files to the channels where they need to. Even if we support this feature, it's definitely not the default option.

**Comment by andymckay** [comment]
FYI fixed up the title underlines and added these files to the table of contents so they show up on readthedocs in a later commit http://addons.readthedocs.org/en/latest/index.html

**Pull request merged**
