### PR TITLE
Add default github labels (JSON file)

### PR DESCRIPTION
**Pull request by willdurand**
I used this file to create the standard labels for addons-blog:

```
npx github-labels -t <token> -f -c ./default-github-labels.json
```

### CODE REVIEW

**Comment by muffinresearch** [comment]
This is great, would it be worth adding some docs for this?

**Review by muffinresearch — APPROVED** [review]
r+wc

**Comment by willdurand** [comment]
Let me add some docs.

**Comment by willdurand** [comment]
err I committed to the main branch directly -_-

**Comment by willdurand** [comment]
See: https://addons.readthedocs.io/en/latest/random/github-labels.html ...

**Pull request merged**
